robot:
  name: my_awesome_follower_arm
  port: /dev/cu.usbmodem5AAF2202301  # Follower port
  urdf_path: "/Users/edgarcancino/Documents/Academic/EMAI Thesis/repos/SO-ARM100/Simulation/SO101/so101_new_calib.urdf"
  calibration_dir: "/Users/edgarcancino/Documents/Academic/EMAI Thesis/vla_workspace/.cache/calibration"
  wrist_roll_offset: -90.0 # Degrees
  home_pose: # Degrees
    shoulder_pan.pos: 0.0
    shoulder_lift.pos: -100.0
    elbow_flex.pos: 100.0
    wrist_flex.pos: 50.0
    wrist_roll.pos: -90
    gripper.pos: 0.0

leader:
  name: my_awesome_leader_arm
  port: /dev/cu.usbmodem5AAF2181531

cameras:
  main: 
    id: 0
    rectify: false
    width: 640
    height: 360
  secondary: 
    id: 1
    rectify: false
    width: 640
    height: 360
