robot:
  name: my_awesome_follower_arm
  port: /dev/cu.usbmodem5AAF2202301  # Follower port
  wrist_roll_offset: -90.0 # Degrees
  home_pose: # Degrees
    shoulder_pan.pos: 0.0
    shoulder_lift.pos: 100.0
    elbow_flex.pos: 100.0
    wrist_flex.pos: 50.0
    wrist_roll.pos: 0
    gripper.pos: 0.0

leader:
  name: my_awesome_leader_arm
  port: /dev/cu.usbmodem5AAF2181531

rectification:
  top: false
  wrist: false

cameras:
  top: 0
  wrist: 1
